sudo: required

language: generic

services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - docker run -dt --name ubuntu16 -v $(pwd):/source kylef/swiftenv:1

install:
  - docker exec ubuntu16 /bin/bash -c "swiftenv rehash && cd source && swiftenv install"

script:
  - docker exec ubuntu16 /bin/bash -c "cd source && swift build"
  - docker exec ubuntu16 /bin/bash -c "cd source && swift build -c release"
  - docker exec ubuntu16 /bin/bash -c "cd source && swift test"