os:
  - linux
  - osx
language: generic
dist: trusty
osx_image: xcode8
notifications:
  email:
    on_success: never
    on_failure: change
install:
  - source ./.travis/install.sh
script:
  - swift build
  - swift build -c release
  - swift test