sudo: required

language: generic

services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - docker run kylef/swiftenv:1
  - docker ps -a

script:
  - swift build
  - swift build -c release
  - swift test